### ISSUE TITLE
cannot initiate using var

### ISSUE THREAD

**Issue by imjeffparedes** [sallar/sqs-parallel#2]
**Code**
`var SqsParallel = require('sqs-parallel')`

**Error**
SyntaxError: Unexpected token =

Im using node.js version 9.7.1

What could be the problem?

**Comment by sallar** [comment]
@imjeffparedes Sorry I missed this. Will check it out :)

**Comment by sallar** [comment]
@imjeffparedes using `var` shouldn't make a difference. However, could you do something like this to see if it works?

```js
const { SqsParallel } = require('sqs-parallel');
```

**Comment by imjeffparedes** [comment]
I skipped this project. Haven't tried your solution but thanks anyway :)
